language: erlang
otp_release:
  - 17.0
  - 17.0.1
  - 17.0.2
  - 17.1
  - 17.1.1
  - 17.1.2
  - 17.2
  - 17.2.1
  - 17.2.2
  - 17.3
  - 17.3.1
  - 17.3.2
  - 17.3.3
  - 17.3.4
  - 17.4
  - 17.4.1
  - 17.5
  - 17.5.1
  - 17.5.2
  - 17.5.3
  - 17.5.4
  - 17.5.5
  - 17.5.6
  - 17.5.6.1
  - 17.5.6.10
  - 17.5.6.2
  - 17.5.6.3
  - 17.5.6.4
  - 17.5.6.5
  - 17.5.6.6
  - 17.5.6.7
  - 17.5.6.8
  - 17.5.6.9
  - 18.0
  - 18.0.1
  - 18.0.2
  - 18.0.3
  - 18.1
  - 18.1.1
  - 18.1.2
  - 18.1.3
  - 18.1.4
  - 18.1.5
  - 18.2
  - 18.2.1
  - 18.2.2
  - 18.2.3
  - 18.2.4
  - 18.2.4.0.1
  - 18.2.4.1
  - 18.3
  - 18.3.1
  - 18.3.2
  - 18.3.3
  - 18.3.4
  - 18.3.4.1
  - 18.3.4.1.1
  - 18.3.4.10
  - 18.3.4.11
  - 18.3.4.2
  - 18.3.4.3
  - 18.3.4.4
  - 18.3.4.5
  - 18.3.4.6
  - 18.3.4.7
  - 18.3.4.8
  - 18.3.4.9
  - 19.0
  - 19.0.1
  - 19.0.2
  - 19.0.3
  - 19.0.4
  - 19.0.5
  - 19.0.6
  - 19.0.7
  - 19.1
  - 19.1.1
  - 19.1.2
  - 19.1.3
  - 19.1.4
  - 19.1.5
  - 19.1.6
  - 19.1.6.1
  - 19.2
  - 19.2.1
  - 19.2.2
  - 19.2.3
  - 19.2.3.1
  - 19.3
  - 19.3.1
  - 19.3.2
  - 19.3.3
  - 19.3.4
  - 19.3.5
  - 19.3.6
  - 19.3.6.1
  - 19.3.6.10
  - 19.3.6.11
  - 19.3.6.12
  - 19.3.6.13
  - 19.3.6.2
  - 19.3.6.3
  - 19.3.6.4
  - 19.3.6.5
  - 19.3.6.6
  - 19.3.6.7
  - 19.3.6.8
  - 19.3.6.9
  - 20.0
  - 20.0.1
  - 20.0.2
  - 20.0.3
  - 20.0.4
  - 20.0.5
  - 20.1
  - 20.1.1
  - 20.1.2
  - 20.1.3
  - 20.1.4
  - 20.1.5
  - 20.1.6
  - 20.1.7
  - 20.1.7.1
  - 20.2
  - 20.2.0.1
  - 20.2.1
  - 20.2.2
  - 20.2.3
  - 20.2.4
  - 20.3
  - 20.3.1
  - 20.3.2
  - 20.3.2.1
  - 20.3.3
  - 20.3.4
  - 20.3.5
  - 20.3.6
  - 20.3.7
  - 20.3.8
  - 20.3.8.1
  - 20.3.8.10
  - 20.3.8.11
  - 20.3.8.12
  - 20.3.8.13
  - 20.3.8.14
  - 20.3.8.15
  - 20.3.8.16
  - 20.3.8.17
  - 20.3.8.18
  - 20.3.8.19
  - 20.3.8.2
  - 20.3.8.20
  - 20.3.8.21
  - 20.3.8.22
  - 20.3.8.23
  - 20.3.8.3
  - 20.3.8.4
  - 20.3.8.5
  - 20.3.8.6
  - 20.3.8.7
  - 20.3.8.8
  - 20.3.8.9
  - 21.0
  - 21.0.1
  - 21.0.2
  - 21.0.3
  - 21.0.4
  - 21.0.5
  - 21.0.6
  - 21.0.7
  - 21.0.8
  - 21.0.9
  - 21.1
  - 21.1.1
  - 21.1.2
  - 21.1.3
  - 21.1.4
  - 21.2
  - 21.2.1
  - 21.2.2
  - 21.2.3
  - 21.2.4
  - 21.2.5
  - 21.2.6
  - 21.2.7
  - 21.3
  - 21.3.1
  - 21.3.2
  - 21.3.3
  - 21.3.4
  - 21.3.5
  - 21.3.6
  - 21.3.7
  - 21.3.7.1
  - 21.3.8
  - 21.3.8.1
  - 21.3.8.10
  - 21.3.8.2
  - 21.3.8.3
  - 21.3.8.4
  - 21.3.8.5
  - 21.3.8.6
  - 21.3.8.7
  - 21.3.8.8
  - 21.3.8.9
  - 22.0
  - 22.0.1
  - 22.0.2
  - 22.0.3
  - 22.0.4
  - 22.0.5
  - 22.0.6
  - 22.0.7
  - 22.1
  - 22.1.1
  - 22.1.2
  - 22.1.3
  - 22.1.4
  - 22.1.5

script: asdf plugin-test elixir https://github.com/asdf-vm/asdf-elixir.git 'elixir --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
